# THis will automatically format every push on main branch. 

name: Format

on:
  pull_request:
    branches:
      - main
      
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: axel-op/googlejavaformat-action@v3.4.0
        with:
          args: "--replace --aosp"
          commitMessage: "${{ github.event.head_commit.message }} format"
