# THis will automatically format every push on main branch. 

name: Rendu Hebdomadaire 

on:
  push:
    branches:    
      - main
      
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: rendu-hebdomadaire
          path: ./src/
