# THis will automatically format every push on main branch. 

name: Rendu

on:
  push:
    branches:    
      - main
      
jobs:
  rendu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/upload-artifact@v2
        with:
          name: rendu
          path: src/main/java
